name: update-code-push
on: [push]
jobs:
  push-step-1:
    runs-on: self-hosted
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HUBADMIN_KEY }}
        if_key_exists: replace ### replace|ignore|fail; optional (defaults to fail)
        known_hosts: |
          ${{ secrets.KNOWN_HOSTS_DEV_PURR_PURDUE_EDU }}
          ${{ secrets.KNOWN_HOSTS_STAGE_CMKC_HUBZERO_ORG }}
#    - name: dev push to stage.cmkc.hubzero.org
#      run: |
#        echo "Checking if freeze-auto-deployments file exists and conditionally stashing and pulling"
#        ssh hubadmin@stage.cmkc.hubzero.org "
#          if [ ! -f /var/www/stage/freeze-auto-deployments ]; then
#            echo "No freeze-auto-deployments file found. Proceeding with stash and pull."
#            echo \"$(date) - No freeze-auto-deployments file found. Stashing and pulling.\" >> /var/www/stage/auto-deployments.log
#            cd /var/www/stage/;
#            git stash -u >> /var/www/stage/auto-deployments.log 2>&1;
#            git pull >> /var/www/stage/auto-deployments.log 2>&1;
#            echo \"$(date) - Stash and pull completed.\" >> /var/www/stage/auto-deployments.log
#          else
#            echo "freeze-auto-deployments file exists. Skipping stash and pull."
#            echo \"$(date) - freeze-auto-deployments file exists. Stash and pull skipped.\" >> /var/www/stage/auto-deployments.log
#          fi
#        "
    - name: dev push to dev.purr.purdue.edu
      run: |
        echo "Checking if freeze-auto-deployments file exists and conditionally stashing and pulling"
        ssh -o StrictHostKeyChecking=no hubadmin@dev.purr.purdue.edu '
          if [ ! -f /var/www/dev/freeze-auto-deployments ]; then
            echo "No freeze-auto-deployments file found. Proceeding with stash and pull."
            echo "$(date) ----------------------------------------- begin auto deployment"
            echo "$(date) - No freeze-auto-deployments file found. Stashing and pulling." >> /var/www/dev/auto-deployments.log
            cd /var/www/dev/;
            git pull origin dev >> /var/www/dev/auto-deployments.log 2>&1;
            git stash -u >> /var/www/dev/auto-deployments.log 2>&1;
            git pull --ff-only >> /var/www/dev/auto-deployments.log 2>&1;
            echo "$(date) ----------------------------------------- end auto deployment"
          else
            echo "freeze-auto-deployments file exists. Skipping stash and pull."
            echo "$(date) - freeze-auto-deployments file exists, auto deployment skipped." >> /var/www/dev/auto-deployments.log
          fi
        '
